spin_manifest_version = 2

[application]
name = "cron"
version = "0.1.0"
authors = ["Thorsten Hans <thorsten.hans@fermyon.com>"]
description = ""

[[trigger.command]]
component = "job"

[component.job]
source = "target/wasm32-wasip2/release/job.wasm"
allowed_outbound_hosts = ["https://myip.fermyon.app/"]
build = ["cargo build --target wasm32-wasip2 --release"]
